stages:
  - test
  - name: release
    if: tag IS present

os: linux

language: python

cache: pip

install:
  - pip install tox

script: tox

jobs:
  include:
    - stage: test
      python: 3.6
      env: TOXENV=py,codecov
    - stage: test
      python: 3.7
      env: TOXENV=py,codecov
    - stage: test
      python: 3.7
      env: TOXENV=lint
    - stage: test
      python: 3.7
      env: TOXENV=docs
    - stage: release
      python: 3.7
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: "__token__"
        distributions: sdist bdist_wheel
        on:
          tags: true
        password:
          secure: "DFhkdYdo1Xsd5bc+xlQrARAqhUICOV4PFXnXfbwXo2zAYUiiCiGrBIo+LiwIgYouv/h+QCaelIBA9b8efJc1k7o7CV7zDKF2304mFy8Wl3mys6puSMIl0py/xKFN/RM4CGgVn/9Ywrto1qpeobDYcsW8vu0UlovfvwA0NG1CmFDAzV+OMlsxV2fnzEvDhClEIA7Py84zaWbjChXHBmiRA7fFGaMGYx45e9eXbALYh/V/nR6NhXwUoBItqkpXRZxYL9FQdQhQ9B5BFpNlGWxA5o6zL5AzElvwqGbE2A+fmoES+T0+wE0SR21zTXmktURZxMPw2gLerhFBymo91hEfqIC9u4YMNKJBIqHGEoC/1uKvREuUOieRMp49EqCawLOmu68EY+jOI6jJvUjATsYK4XK91xfxbFjmlr9hq2MGJzd8SdNw7jRVdZOq08jQWne3F/urlLZ4uNf9fZFewH0xDBpn0GEX/DQ1ce2izeHStdXpcwTaV9o3gASc9pzRjxyx/JPEVd9nbe0IS+mhxxmwwTZCf077A+FGG5C/cNtPkI5arD8SQfYds9PS9k7kVFuwieX1SZ+WMHJzgy8pqOs3F7p7jm/r1agotDzhSx+tt25g4Wn02I4GZLtxMwhsLzh550GKFfZmyX0Nes4rcSGE1qMZSk/2es7IXhaZagkbpkM="
